/// Flutter icons BottomAppBarIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomAppBarIcons
///      fonts:
///       - asset: fonts/Icons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BottomAppBarIcons {
  BottomAppBarIcons._();

  static const _kFontFam = 'Icons';
  static const _kFontPkg = null;

  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pitch = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
